name: hangman
version: 0.1.0.0
github: "OlaoluwaM/hangman"
license: BSD-3-Clause
author: "Olaoluwa Mustapha"
maintainer: "37044906+OlaoluwaM@users.noreply.github.com"
copyright: "2024 Olaoluwa Mustapha"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - data/dict.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A hangman game written in Haskell

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

language: Haskell2010

executables:
  hangman:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hangman
      - split
      - random
      - containers
      - PyF
      - lens
    default-extensions:
      - LambdaCase
      - QuasiQuotes
    when:
      - condition: false
        other-modules: Paths_hangman

tests:
  hangman-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hangman
